<<<<<<< HEAD
import { Encode_Sans } from "next/font/google";
import "./globals.css";

const encodeSans = Encode_Sans({
  variable: "--font-encode-sans",
  subsets: ["latin"],
  weight: ["300", "400", "500", "700"],
});

export const metadata = {
  title: "React Assignment",
  description: "Dynamic Product Lising Page",
=======
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/Components/Navbar";
import Dataprovider from "@/Context/Data";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "TANN TRIM",
  description: "Generated by create next app",
>>>>>>> 122c814d7892a5abae7310f881cd7a8dc2d56733
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
<<<<<<< HEAD
      <body className={encodeSans.variable}>
        {children}
=======
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
         <Dataprovider>
        <Navbar />
        {children}
        </Dataprovider>
>>>>>>> 122c814d7892a5abae7310f881cd7a8dc2d56733
      </body>
    </html>
  );
}
